---
title: "Course Syllabus"
subtitle: "All the official information"
bibliography: references.bib
csl: apa7.csl
---

::: {.content-visible when-format="html"}
Module Handbook Link **Click here to download a PDF copy of the
syllabus.**
:::

## Student hours

**Student hours**: Monday 13:30-14:30 in person (or by appointment) -
and I tour all the Labs every week, so grab me if you see me! You'll get
to realise that I am VERY available and always keen to talk!

## Textbooks

There is an extensive reading list provided for general overview texts.
These are primarily available online and via the Goldsmiths Library.
They can be accessed from the [Reading List module on the
VLE](https://learn.gold.ac.uk/mod/aspirelists/view.php?id=1176296)

|                                                                                                                                                                                                                                                                 |                               |      |                                  |
|----------------|----------------|----------------|-------------------------|
| Book                                                                                                                                                                                                                                                            | Authors                       | Date | Availability                     |
| [Research Methods in Psychology](https://gold.rl.talis.com/link?url=http%3A%2F%2Fwww.vlebooks.com%2Fvleweb%2Fproduct%2Fopenreader%3Fid%3DGoldsmiths%26isbn%3D9781292134307&sig=ae7bd42170148e3755899970fd3dcdad006a06f6ec045e10298ea8d0619727c7)                | Howitt & Cramer               | 2017 | Available ONLINE via the Library |
| [Research Methods in Psychology](https://gold.rl.talis.com/link?url=http%3A%2F%2Fwww.vlebooks.com%2Fvleweb%2Fproduct%2Fopenreader%3Fid%3DGoldsmiths%26isbn%3D9781446260272&sig=f6330095d858026a17e25a5ad43e3d84a7ed831f7f3dbe768dac351be4be90dd)                | Breakwell, Smith & Wright     | 2012 | Available ONLINE via the Library |
| [Research Methods and Statistics in Psychology](https://gold.rl.talis.com/link?url=http%3A%2F%2Fwww.vlebooks.com%2Fvleweb%2Fproduct%2Fopenreader%3Fid%3DGoldsmiths%26isbn%3D9781446297575&sig=b00637a977e95e577769fa79984def8086133d1100cd6835bde0bba0620ad037) | Haslam & McGarty              | 2014 | Available ONLINE via the Library |
| [Research Methods, Design & Analysis](https://gold.rl.talis.com/link?url=http%3A%2F%2Fwww.vlebooks.com%2Fvleweb%2Fproduct%2Fopenreader%3Fid%3DGoldsmiths%26isbn%3D9781292068466&sig=b829586f1b6fec828139eff4275271703f8d34976954704dcd69a981b39560eb)           | Christensen, Johnson & Turner | 2015 | Available ONLINE via the Library |
| [SPSS for Psychologists: (and everybody else)](https://gold.rl.talis.com/link?url=http%3A%2F%2Fwww.vlebooks.com%2Fvleweb%2Fproduct%2Fopenreader%3Fid%3DGoldsmiths%26isbn%3D9781137579232&sig=0347105461363799b4398d8fc27d54de765488c2ebee1cf700d1c7aa21629a54)  | Brace, Kemp & Snelgar         | 2016 | Available ONLINE via the Library |

## Course learning outcomes

**Students who successfully complete this module will be able to:**

-   Show a critical understanding of research design and methodology
-   Design, conduct, analyse, interpret and disseminate psychological
    research 
-   Understand the conceptual and historical issues concerned with
    psychology as a science and area of practical application
-   Demonstrate valuable time-management and collaborative
    project-management skills and proficiencies
-   Reflect on their own learning, skill development and metacognition,
    preparing them for the final year dissertation

