---
title: "PS52007D - Research Methods in Psychology 2022/3"
subtitle: "Module Coordinator - Dr. Gordon Wright"
execute:
  freeze: false
---

This page cjiiontains an outline of the topics, content, and assignments
for the semester. Note that this schedule will be updated as the
semester progresses and the timeline of topics and assignments might be
updated throughout the semester.

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/1ZsmGNXF5fZuNbkGsYRnFxhDKS9fZJQdtOg2Cw3KlrtQ/edit?usp=sharing", sheet = "TopLevel")
```

::: column-screen-right
```{r, echo = FALSE}
d %>%
  mutate(
    Date = as.Date(Date),
    Week = ifelse(is.na(Week), "", Week)
  ) %>%
  gt() %>%

  text_transform(cells_body(columns = c(Prep)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("book", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('book')}</a>")
      )
    }
  ) %>%
  text_transform(cells_body(columns = c(Slides)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("laptop", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('laptop')}</a>")
      )
    }
  ) %>%
  text_transform(cells_body(columns = c(Readings)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("users", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('users')}</a>")
      )
    }
  ) %>%
  text_transform(cells_body(columns = c(hw)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("keyboard", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('keyboard')}</a>")
      )
    }
  ) %>%
  text_transform(cells_body(columns = c(Skills)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("users-rectangle", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('users-rectangle')}</a>")
      )
    }
  ) %>%
  text_transform(cells_body(columns = c(Extra)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("file-circle-check", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('file-circle-check')}</a>")
      )
    }
  ) %>%
  text_transform(cells_body(columns = c(MiniDiss)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("users", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('users')}</a>")
      )
    }
  ) %>%
  fmt_date(Date, date_style = 9) %>%
  sub_missing(columns = c(Date, Session, Topic, Notes), missing_text = "") %>%
  cols_align(
    align = "center", 
    columns = c(Week, Prep, Slides, Readings, hw, Skills, Extra, MiniDiss)
    ) %>%
  cols_align(
    align = "left", 
    columns = c(Date, Session, Topic, Notes)
    )  %>%
opt_row_striping(data = , row_striping = TRUE) %>% 

tab_header(title = md("TABLE TITLE 2007"))  %>%
     tab_style(
     locations = cells_column_labels(columns = everything()),
     style     = list(
       #Give a thick border below
       cell_borders(sides = "bottom", weight = px(3)),
       #Make text bold
       cell_text(weight = "bold")
     )
   ) %>% 
   #Apply different style to the title
   tab_style(
     locations = cells_title(groups = "title"),
     style     = list(
       cell_text(weight = "bold", size = 24)
     )
   )

```
:::
